# config/assets.yaml

# Haupteinstellungen für die Energie-Studie deiner Bachelorarbeit
energy:
  # Auswahl der ersten 20+ Assets (ETFs und Einzelaktien aus dem Energiesektor)
  tickers:
    - "XLE"     # Energy Select Sector SPDR Fund
    - "ICLN"    # iShares Global Clean Energy ETF
    - "XDW0.L"  # Xtrackers MSCI World Energy
    - "NRJ.PA"  # Amundi MSCI New Energy
    - "STNX.SW" # SPDR MSCI Europe Energy
    - "SXLE.L"  # SPDR S&P U.S. Energy Select Sector
    - "EXH1.DE" # iShares STOXX Europe 600 Oil & Gas
    - "IE00BK5BCH80.SG"        # L&G Clean Energy

    - "XOM"     # Exxon Mobil 
    - "SHEL.L"  # Shell 
    - "BP.L"    # BP
    - "TTE.PA"  # TotalEnergies
    - "ENR.DE"  # Siemens Energy AG
    - "REP.MC"  # Repsol
    - "VWS.CO"  # Vestas Wind
    - "FSLR"    # First Solar
    - "JKS"     # Jinko Solar

    - "CL=F"    # Crude Oil
    - "NG=F"    # Natural Gas


  # Parameter für den Daten-Download und die Extraktion
  settings:
    start_date: "2020-01-01"
    target_column: "Close"
    interval: "1d"  # Täglich für den Benchmark

# Zusätzliche Benchmarks (Optional für später)
benchmarks:
  dax: ["^GDAXI"]
  gold: ["GC=F"]