energy_assets:
- symbol: XOM
  name: Exxon Mobil Corp.
- symbol: CVX
  name: Chevron Corp.
- symbol: SHEL
  name: Shell PLC
- symbol: TTE
  name: TotalEnergies SE
- symbol: BP
  name: BP PLC
- symbol: RELIANCE.NS
  name: Reliance Industries
- symbol: E
  name: Eni SpA
- symbol: EQNR
  name: Equinor ASA
- symbol: REP.MC
  name: Repsol SA
- symbol: OMV.VI
  name: OMV AG
- symbol: SU
  name: Suncor Energy Inc.
- symbol: COP
  name: ConocoPhillips
- symbol: EOG
  name: EOG Resources Inc.
- symbol: CNQ
  name: Canadian Natural Resources
- symbol: OXY
  name: Occidental Petroleum
- symbol: WDS
  name: Woodside Energy Group
- symbol: DVN
  name: Devon Energy Corp.
- symbol: CTRA
  name: Coterra Energy Inc.
- symbol: APA
  name: APA Corp.
- symbol: OVV
  name: Ovintiv Inc.
- symbol: STO.AX
  name: Santos Ltd.
- symbol: 1605.T
  name: Inpex Corp.
- symbol: EQT
  name: EQT Corp.
- symbol: RRC
  name: Range Resources Corp.
- symbol: SLB
  name: Schlumberger Ltd.
- symbol: HAL
  name: Halliburton Co.
- symbol: BKR
  name: Baker Hughes Co.
- symbol: FTI
  name: TechnipFMC PLC
- symbol: RIG
  name: Transocean Ltd.
- symbol: PTEN
  name: Patterson-UTI Energy
- symbol: HP
  name: Helmerich & Payne Inc.
- symbol: TDW
  name: Tidewater Inc.
- symbol: SPM.MI
  name: Saipem SpA
- symbol: ENB
  name: Enbridge Inc.
- symbol: EPD
  name: Enterprise Products Partners
- symbol: TRP
  name: TC Energy Corp.
- symbol: WMB
  name: Williams Companies Inc.
- symbol: LNG
  name: Cheniere Energy Inc.
- symbol: ET
  name: Energy Transfer LP
- symbol: PAA
  name: Plains All American Pipeline
- symbol: VLO
  name: Valero Energy Corp.
- symbol: DK
  name: Delek US Holdings
- symbol: 5019.T
  name: Idemitsu Kosan Co.
- symbol: 0883.HK
  name: CNOOC Ltd.
- symbol: 0857.HK
  name: PetroChina Co. Ltd.
- symbol: SM
  name: SM Energy Co.
- symbol: FSLR
  name: First Solar
- symbol: NEE
  name: NextEra Energy
- symbol: PLUG
  name: Plug Power
- symbol: CCJ
  name: Cameco Corporation
- symbol: RWEOY
  name: RWE AG (US ADR)
- symbol: DUK
  name: Duke Energy Corp
- symbol: XEL
  name: Xcel Energy
- symbol: SO
  name: Southern Company (Southeast US)
- symbol: D
  name: Dominion Energy (Mid-Atlantic)
- symbol: EXC
  name: Exelon (Nuclear)
- symbol: PCG
  name: PG&E (California)
- symbol: ED
  name: Consolidated Edison (NY)
- symbol: DTE
  name: DTE Energy (Michigan)
- symbol: CVE.TO
  name: Cenovus Energy Inc.
- symbol: IBE.MC
  name: Iberdrola SA
- symbol: ENGI.PA
  name: Engie SA
- symbol: 9501.T
  name: Tokyo Electric Power (TEPCO)
- symbol: 9532.T
  name: Osaka Gas Co.
- symbol: IOC.NS
  name: Indian Oil Corp.
- symbol: 0002.HK
  name: CLP Holdings Ltd.
- symbol: CSIQ
  name: Canadian Solar Inc.
- symbol: DNN
  name: Denison Mines Corp.
- symbol: UEC
  name: Uranium Energy Corp.
- symbol: CQP
  name: Cheniere Energy Partners LP
